# Adaptive Tutorial POC

## 🚀 Overview

This project is a proof-of-concept (POC) for an adaptive tutorial system implemented as a web-based chat assistant named **CIELO** (Conversational Intelligent Emotional Learning Operator).

It uses a **Retrieval-Augmented Generation (RAG)** architecture to answer questions about a car's driver-assistance features. The assistant first assesses the user's prior knowledge and then uses that context to initiate a chat. The chat assistant's knowledge is sourced *exclusively* from a provided handbook, which is ingested into a vector database.

## ✨ Features

  * **Adaptive Onboarding:** Greets the user with a dynamic welcome message based on their self-assessed knowledge scores.
  * **RAG Chat:** Uses a LangChain.js backend to retrieve relevant document chunks from a vector store (HNSWLib) and generate accurate answers using an OpenAI model (GPT-4o).
  * **Context-Aware:** Maintains chat history to hold a stateful conversation.
  * **Dynamic Media:** The frontend can parse special tags from the AI's response (e.g., `[SHOW_CHAPTER: Spurführung]`) to display relevant GIFs and images in the chat interface.

## 💻 Technology Stack

  * **Frontend:** Vanilla HTML, CSS, and JavaScript (no framework).
  * **Backend:** Node.js with Express.
  * **AI & RAG:**
      * **Orchestration:** LangChain.js (`langchain`).
      * **LLM:** OpenAI (GPT-4o specified in `server.js`).
      * **Embeddings:** `OpenAIEmbeddings`.
      * **Vector Store:** HNSWLib (`hnswlib-node`) for local vector search.

-----

## 📁 Project Structure

```
adaptive-tutorial-poc-feature-rag-chat-assistant/
├── backend/
│   ├── vector_index/       # Generated by the ingest script
│   │   ├── args.json
│   │   ├── docstore.json
│   │   └── hnswlib.index
│   ├── handbook.js         # Source of truth: JSON data for all features
│   ├── handbook.txt        # (Appears to be a text-based version, not used by ingest)
│   ├── ingest_handbook.js  # --- (Key File) --- Script to create the vector index
│   ├── package.json
│   ├── package-lock.json
│   └── server.js           # --- (Key File) --- The Express backend server
│
├── frontend/
│   ├── index.html          # The main HTML structure
│   ├── logo.png            # CIELO logo
│   └── script.js           # --- (Key File) --- All client-side logic
│
└── .gitignore              # Ignores .env, node_modules, etc.
```

-----

## 🔧 Key Files & Functions

### `backend/ingest_handbook.js`

This is a one-time setup script used to "ingest" the knowledge source (`handbook.js`) and create the vector database.

  * **`run()`**: The main asynchronous function.
    1.  **Load Data:** Reads `handbook.js` from the disk.
    2.  **Extract Text:** Parses the JSON and iterates through all chapters, concatenating the chapter titles and the `texts` arrays into a single large string.
    3.  **Split:** Uses `RecursiveCharacterTextSplitter` to break the large string into smaller, semantically meaningful chunks (chunk size 500, overlap 50).
    4.  **Embed & Store:** Uses `OpenAIEmbeddings` to create vector embeddings for each chunk and then uses `HNSWLib.fromDocuments` to build the vector store from these documents and embeddings.
    5.  **Save:** Saves the generated vector index to the `backend/vector_index` directory.

### `backend/server.js`

This file is the Node.js Express server that runs the entire application, handling API requests and managing the AI logic.

  * **`initializeAI()`**: This crucial function runs on server startup.

    1.  **Load Store:** Loads the pre-built vector index from the `vector_index` directory using `HNSWLib.load`.
    2.  **Create Retriever:** Creates a `retriever` from the loaded vector store.
    3.  **Define Prompt:** Creates a `ChatPromptTemplate` that instructs the AI (CIELO) on its persona, its constraints (answer *only* from context), and the special rule to add ` [SHOW_CHAPTER: ...]  ` tags when explaining a feature.
    4.  **Create Chain:** Defines the core RAG logic using `RunnableSequence`. This chain automatically:
          * Retrieves context from the vector store based on the user's `question`.
          * Passes along the `chat_history` and `question`.
          * Formats the prompt with all this information.
          * Sends the final prompt to the `ChatOpenAI` model.
          * Parses the output as a string.

  * **`POST /start-chat`**:

      * Triggered by the frontend's initial assessment form.
      * Creates a unique `sessionId` and stores the user's `scores`.
      * Crafts a dynamic welcome question (e.g., "I see you want to learn about...
        ") and runs it through the AI chain to get a natural-sounding welcome message.
      * Saves this first message as the start of the `session.history`.

  * **`POST /chat-message`**:

      * Handles all subsequent messages from the user.
      * Formats the session's chat history into LangChain's `HumanMessage` and `AIMessage` objects.
      * Invokes the `chain` with the new user message (`question`) and the formatted history (`chat_history`).
      * Adds the user's message and the AI's response to the session history to maintain context.
      * Returns the raw AI response to the frontend.

### `frontend/script.js`

This file contains all the client-side logic for rendering the UI, managing state, and communicating with the backend.

  * **`buildAssessmentForm()`**: Dynamically generates the HTML for the initial slider-based questions from the `assessableChapters` object.
  * **`assessmentForm.addEventListener('submit', ...)`**:
      * Handles the submission of the knowledge assessment form.
      * Collects the slider values into a `scores` object.
      * Calls the `POST /start-chat` endpoint with these scores.
      * On success, it saves the `sessionId`, hides the assessment container, displays the chat container, and calls `addMessage` to show the AI's welcome message.
  * **`chatForm.addEventListener('submit', ...)`**:
      * The main chat loop that fires when the user sends a message.
      * It immediately displays the user's message by calling `addMessage(messageText, 'user')`.
      * It sends the message text and `sessionId` to the `POST /chat-message` endpoint.
      * **Media Handling:** When the response is received, it checks the text for the `chapterTagRegex` (e.g., `\[SHOW_CHAPTER: (.*?)\]`).
          * **If a tag is found:** It extracts the chapter name (e.g., "Spurführung"), removes the tag from the AI's message, displays the cleaned text message, and then calls `addMedia(chapterName)` to display the corresponding GIF.
          * **If no tag is found:** It simply displays the AI message as-is.
  * **`addMedia(chapterName)`**:
      * Looks up the `chapterName` in the large, hardcoded `handbookData` object (a copy of `handbook.js` in the frontend).
      * Finds the first media item in that chapter's `media` array and appends an `<img>` tag to the chat, causing the GIF to appear.